/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LoanCommitmentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitmentTimestamp"
      | "contractText"
      | "getContractText"
      | "getMyCommitment"
      | "getMyCommitmentTimestamp"
      | "hasCommitted"
      | "hasUserCommitted"
      | "protocolId"
      | "submitCommitment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CommitmentSubmitted" | "CommitmentViewed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitmentTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractText",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractText",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyCommitmentTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasCommitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserCommitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitCommitment",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitmentTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyCommitmentTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitCommitment",
    data: BytesLike
  ): Result;
}

export namespace CommitmentSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentViewedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanCommitment extends BaseContract {
  connect(runner?: ContractRunner | null): LoanCommitment;
  waitForDeployment(): Promise<this>;

  interface: LoanCommitmentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitmentTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  contractText: TypedContractMethod<[], [string], "view">;

  getContractText: TypedContractMethod<[], [string], "view">;

  getMyCommitment: TypedContractMethod<[], [string], "view">;

  getMyCommitmentTimestamp: TypedContractMethod<[], [bigint], "view">;

  hasCommitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasUserCommitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitCommitment: TypedContractMethod<
    [encryptedAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitmentTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "contractText"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContractText"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyCommitment"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyCommitmentTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCommitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUserCommitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitCommitment"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommitmentSubmitted"
  ): TypedContractEvent<
    CommitmentSubmittedEvent.InputTuple,
    CommitmentSubmittedEvent.OutputTuple,
    CommitmentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentViewed"
  ): TypedContractEvent<
    CommitmentViewedEvent.InputTuple,
    CommitmentViewedEvent.OutputTuple,
    CommitmentViewedEvent.OutputObject
  >;

  filters: {
    "CommitmentSubmitted(address,uint256)": TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;
    CommitmentSubmitted: TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;

    "CommitmentViewed(address)": TypedContractEvent<
      CommitmentViewedEvent.InputTuple,
      CommitmentViewedEvent.OutputTuple,
      CommitmentViewedEvent.OutputObject
    >;
    CommitmentViewed: TypedContractEvent<
      CommitmentViewedEvent.InputTuple,
      CommitmentViewedEvent.OutputTuple,
      CommitmentViewedEvent.OutputObject
    >;
  };
}
